/*******************************************************************************
 * Copyright 2014 Persistent Systems Ltd.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Azure.DataCenterMigration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProgressResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProgressResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Azure.DataCenterMigration.ProgressResources", typeof(ProgressResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blob copy completed from {0} to {1}.
        /// </summary>
        internal static string BlobCopyCompleted {
            get {
                return ResourceManager.GetString("BlobCopyCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blob copy started from {0} to {1}.
        /// </summary>
        internal static string BlobCopyStarted {
            get {
                return ResourceManager.GetString("BlobCopyStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blob is already exist in destination. ContainerName: {0} , Blob Name: {1}, Storage Account Name {2}.
        /// </summary>
        internal static string BlobExistsInDestination {
            get {
                return ResourceManager.GetString("BlobExistsInDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/{1} bytes copied.
        /// </summary>
        internal static string BytesCopied {
            get {
                return ResourceManager.GetString("BytesCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked cloud service name {0} availability from Microsoft Azure for subscription.
        /// </summary>
        internal static string CheckServiceNameAvailabilityFromMSAzureCompleted {
            get {
                return ResourceManager.GetString("CheckServiceNameAvailabilityFromMSAzureCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking cloud service name {0} availability from Microsoft Azure for subscription.
        /// </summary>
        internal static string CheckServiceNameAvailabilityFromMSAzureStarted {
            get {
                return ResourceManager.GetString("CheckServiceNameAvailabilityFromMSAzureStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked storage name {0} availability from Microsoft Azure for subscription.
        /// </summary>
        internal static string CheckStorageNameAvailabilityFromMSAzureCompleted {
            get {
                return ResourceManager.GetString("CheckStorageNameAvailabilityFromMSAzureCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking storage name {0} availability from Microsoft Azure for subscription.
        /// </summary>
        internal static string CheckStorageNameAvailabilityFromMSAzureStarted {
            get {
                return ResourceManager.GetString("CheckStorageNameAvailabilityFromMSAzureStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recieved blob {0} information of storage account {1}.
        /// </summary>
        internal static string CloudBlobInfoRecieved {
            get {
                return ResourceManager.GetString("CloudBlobInfoRecieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1} service along with it&apos;s deployment completed.
        /// </summary>
        internal static string CompletedServices {
            get {
                return ResourceManager.GetString("CompletedServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage {0} of {1} completed....
        /// </summary>
        internal static string CompletedStages {
            get {
                return ResourceManager.GetString("CompletedStages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying all blobs to destination....
        /// </summary>
        internal static string CopyAllBlobsToDestination {
            get {
                return ResourceManager.GetString("CopyAllBlobsToDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress : {0} =&gt; {1:0.##} %.
        /// </summary>
        internal static string CopyBlobProgressInPercentage {
            get {
                return ResourceManager.GetString("CopyBlobProgressInPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Blob execution completed : ContainerName: {0} , Blob Name: {1}, Storage Account Name {2} in ({3}:{4}:{5}:{6}).
        /// </summary>
        internal static string CopyBlobToDestinationCompleted {
            get {
                return ResourceManager.GetString("CopyBlobToDestinationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Blob execution started : ContainerName: {0} , Blob Name: {1}, Storage Account Name {2}.
        /// </summary>
        internal static string CopyBlobToDestinationStarted {
            get {
                return ResourceManager.GetString("CopyBlobToDestinationStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Affinity Groups....
        /// </summary>
        internal static string CreateAffinityGroups {
            get {
                return ResourceManager.GetString("CreateAffinityGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Cloud Services and it&apos;s Deployments....
        /// </summary>
        internal static string CreateCloudServices {
            get {
                return ResourceManager.GetString("CreateCloudServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Storage Accounts....
        /// </summary>
        internal static string CreateStorageAccounts {
            get {
                return ResourceManager.GetString("CreateStorageAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Virtual Networks....
        /// </summary>
        internal static string CreateVirtualNetworks {
            get {
                return ResourceManager.GetString("CreateVirtualNetworks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting the affinity group {0} as it is started creating and the corresponding thread is got cancelled later..
        /// </summary>
        internal static string DeleteAGOnTaskCancelled {
            get {
                return ResourceManager.GetString("DeleteAGOnTaskCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting the cloud service {0} as it is started creating and the corresponding thread is got cancelled later..
        /// </summary>
        internal static string DeleteCloudServiceOnTaskCancelled {
            get {
                return ResourceManager.GetString("DeleteCloudServiceOnTaskCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure blob copy returned a status of &apos;{0}&apos;
        ///Deleting the blob from destination..
        /// </summary>
        internal static string DeleteNonSuccessBlob {
            get {
                return ResourceManager.GetString("DeleteNonSuccessBlob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting the storage account {0} as it is started creating and the corresponding thread is got cancelled later..
        /// </summary>
        internal static string DeleteStorageAccountOnTaskCancelled {
            get {
                return ResourceManager.GetString("DeleteStorageAccountOnTaskCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting the virtual machine {0} as it is started creating and the corresponding thread is got cancelled later..
        /// </summary>
        internal static string DeleteVirtualMachineOnTaskCancelled {
            get {
                return ResourceManager.GetString("DeleteVirtualMachineOnTaskCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The same ReservedIPName has been assigned to muliple services in json file.The same ReservedIPName can not be assigned to muliple services..
        /// </summary>
        internal static string DuplicateReservedIPName {
            get {
                return ResourceManager.GetString("DuplicateReservedIPName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution Completed.
        /// </summary>
        internal static string ExecutionCompleted {
            get {
                return ResourceManager.GetString("ExecutionCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution Completed in ({0}:{1}:{2}:{3}).
        /// </summary>
        internal static string ExecutionCompletedWithTime {
            get {
                return ResourceManager.GetString("ExecutionCompletedWithTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution Started.
        /// </summary>
        internal static string ExecutionStarted {
            get {
                return ResourceManager.GetString("ExecutionStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exported affinity groups .
        /// </summary>
        internal static string ExportAffinityGroupCompleted {
            get {
                return ResourceManager.GetString("ExportAffinityGroupCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting affinity groups.
        /// </summary>
        internal static string ExportAffinityGroupStarted {
            get {
                return ResourceManager.GetString("ExportAffinityGroupStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud service &apos;{0}&apos; exported successfully.
        /// </summary>
        internal static string ExportCloudServiceCompleted {
            get {
                return ResourceManager.GetString("ExportCloudServiceCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting cloud services.
        /// </summary>
        internal static string ExportCloudServicesStarted {
            get {
                return ResourceManager.GetString("ExportCloudServicesStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting cloud service &apos;{0}&apos;.
        /// </summary>
        internal static string ExportCloudServiceStarted {
            get {
                return ResourceManager.GetString("ExportCloudServiceStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exported resources for data center &apos;{0}&apos;.
        /// </summary>
        internal static string ExportDataCenterCompleted {
            get {
                return ResourceManager.GetString("ExportDataCenterCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting resources for data center &apos;{0}&apos;.
        /// </summary>
        internal static string ExportDataCenterStarted {
            get {
                return ResourceManager.GetString("ExportDataCenterStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployment details &apos;{0}&apos; exported susccessfully for service &apos;{1}&apos;.
        /// </summary>
        internal static string ExportDeploymentCompleted {
            get {
                return ResourceManager.GetString("ExportDeploymentCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting deployment details &apos;{0}&apos; for service &apos;{1}&apos;.
        /// </summary>
        internal static string ExportDeploymentStarted {
            get {
                return ResourceManager.GetString("ExportDeploymentStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata exported at location &apos;{0}&apos;.
        /// </summary>
        internal static string ExportMetadataCompleted {
            get {
                return ResourceManager.GetString("ExportMetadataCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting metadata... .
        /// </summary>
        internal static string ExportMetadataStarted {
            get {
                return ResourceManager.GetString("ExportMetadataStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exported all storage accounts.
        /// </summary>
        internal static string ExportStorageAccountCompleted {
            get {
                return ResourceManager.GetString("ExportStorageAccountCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting all storage accounts.
        /// </summary>
        internal static string ExportStorageAccountStarted {
            get {
                return ResourceManager.GetString("ExportStorageAccountStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exported virtual machine for cloud service &apos;{0}&apos;.
        /// </summary>
        internal static string ExportVirtualMachineCompleted {
            get {
                return ResourceManager.GetString("ExportVirtualMachineCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting virtual machine for cloud service &apos;{0}&apos;.
        /// </summary>
        internal static string ExportVirtualMachineStarted {
            get {
                return ResourceManager.GetString("ExportVirtualMachineStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exported virtual network configuration file.
        /// </summary>
        internal static string ExportVNetConfigurationCompleted {
            get {
                return ResourceManager.GetString("ExportVNetConfigurationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting virtual network configuration file.
        /// </summary>
        internal static string ExportVNetConfigurationStarted {
            get {
                return ResourceManager.GetString("ExportVNetConfigurationStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received affinity groups from Microsoft Azure for subscription.
        /// </summary>
        internal static string GetAffinityGroupsFromMSAzureCompleted {
            get {
                return ResourceManager.GetString("GetAffinityGroupsFromMSAzureCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting affinity groups from Microsoft Azure for subscription.
        /// </summary>
        internal static string GetAffinityGroupsFromMSAzureStarted {
            get {
                return ResourceManager.GetString("GetAffinityGroupsFromMSAzureStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting blob {0} information of storage account {1}.
        /// </summary>
        internal static string GetCloudBlobStarted {
            get {
                return ResourceManager.GetString("GetCloudBlobStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received Deployment information from Microsoft Azure subscription.
        /// </summary>
        internal static string GetDeploymentFromMSAzureCompleted {
            get {
                return ResourceManager.GetString("GetDeploymentFromMSAzureCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Deployment information from Microsoft Azure subscription.
        /// </summary>
        internal static string GetDeploymentFromMSAzureStarted {
            get {
                return ResourceManager.GetString("GetDeploymentFromMSAzureStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received cloud services from Microsoft Azure for subscription.
        /// </summary>
        internal static string GetServicesFromMSAzureCompleted {
            get {
                return ResourceManager.GetString("GetServicesFromMSAzureCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting cloud services from Microsoft Azure for subscription.
        /// </summary>
        internal static string GetServicesFromMSAzureStarted {
            get {
                return ResourceManager.GetString("GetServicesFromMSAzureStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received storage account key from Microsoft Azure for account {0}.
        /// </summary>
        internal static string GetStorageAccountKeysCompleted {
            get {
                return ResourceManager.GetString("GetStorageAccountKeysCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting storage account key from Microsoft Azure for account {0}.
        /// </summary>
        internal static string GetStorageAccountKeysStarted {
            get {
                return ResourceManager.GetString("GetStorageAccountKeysStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received storage account from Microsoft Azure for subscription.
        /// </summary>
        internal static string GetStorageAccountsFromMSAzureCompleted {
            get {
                return ResourceManager.GetString("GetStorageAccountsFromMSAzureCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting storage accounts from Microsoft Azure for subscription.
        /// </summary>
        internal static string GetStorageAccountsFromMSAzureStarted {
            get {
                return ResourceManager.GetString("GetStorageAccountsFromMSAzureStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received virtual machines information from Microsoft Azure subscription.
        /// </summary>
        internal static string GetVirtualMachinesFromMSAzureCompleted {
            get {
                return ResourceManager.GetString("GetVirtualMachinesFromMSAzureCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Virtual machines information from Microsoft Azure subscription.
        /// </summary>
        internal static string GetVirtualMachinesFromMSAzureStarted {
            get {
                return ResourceManager.GetString("GetVirtualMachinesFromMSAzureStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received virtual network configuration from Microsoft Azure for subscription.
        /// </summary>
        internal static string GetVirtualNetworkConfigFromMSAzureCompleted {
            get {
                return ResourceManager.GetString("GetVirtualNetworkConfigFromMSAzureCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting virtual network configuration from Microsoft Azure for subscription.
        /// </summary>
        internal static string GetVirtualNetworkConfigFromMSAzureStarted {
            get {
                return ResourceManager.GetString("GetVirtualNetworkConfigFromMSAzureStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affinity group &apos;{0}&apos; created successfully in ({1}:{2}:{3}:{4}).
        /// </summary>
        internal static string ImportAffinityGroupCompleted {
            get {
                return ResourceManager.GetString("ImportAffinityGroupCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affinity group creation failed with status : &apos;{0}&apos;.
        /// </summary>
        internal static string ImportAffinityGroupFailed {
            get {
                return ResourceManager.GetString("ImportAffinityGroupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating affinity group &apos;{0}&apos; in destination subscription..
        /// </summary>
        internal static string ImportAffinityGroupStarted {
            get {
                return ResourceManager.GetString("ImportAffinityGroupStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All the resources for data center &apos;{0}&apos; are successfully imported on destination subscription.
        /// </summary>
        internal static string ImportDataCenterCompleted {
            get {
                return ResourceManager.GetString("ImportDataCenterCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing resources to data center &apos;{0}&apos;.
        /// </summary>
        internal static string ImportDataCenterStarted {
            get {
                return ResourceManager.GetString("ImportDataCenterStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployment &apos;{0}&apos; completed for VM :  {1} in ({2}:{3}:{4}:{5}).
        /// </summary>
        internal static string ImportDeploymentCompleted {
            get {
                return ResourceManager.GetString("ImportDeploymentCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployment &apos;{0}&apos; started for VM :  {1}..
        /// </summary>
        internal static string ImportDeploymentStarted {
            get {
                return ResourceManager.GetString("ImportDeploymentStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata Imported successfully,.
        /// </summary>
        internal static string ImportMetadataCompleted {
            get {
                return ResourceManager.GetString("ImportMetadataCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing metadata from file &apos;{0}&apos; .. .
        /// </summary>
        internal static string ImportMetadataStarted {
            get {
                return ResourceManager.GetString("ImportMetadataStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service &apos;{0}&apos; created successfully in ({1}:{2}:{3}:{4}).
        /// </summary>
        internal static string ImportServiceCompleted {
            get {
                return ResourceManager.GetString("ImportServiceCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service creation failed with status : &apos;{0}&apos;.
        /// </summary>
        internal static string ImportServiceFailed {
            get {
                return ResourceManager.GetString("ImportServiceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating service &apos;{0}&apos; in destination subscription..
        /// </summary>
        internal static string ImportServiceStarted {
            get {
                return ResourceManager.GetString("ImportServiceStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage account &apos;{0}&apos; created successfully in ({1}:{2}:{3}:{4}).
        /// </summary>
        internal static string ImportStorageAccountCompleted {
            get {
                return ResourceManager.GetString("ImportStorageAccountCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage account creation failed with status : &apos;{0}&apos;.
        /// </summary>
        internal static string ImportStorageAccountFailed {
            get {
                return ResourceManager.GetString("ImportStorageAccountFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating storage account &apos;{0}&apos; in destination subscription..
        /// </summary>
        internal static string ImportStorageAccountStarted {
            get {
                return ResourceManager.GetString("ImportStorageAccountStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual machine &apos;{0}&apos; created successfully for deployment {1} in ({2}:{3}:{4}:{5}).
        /// </summary>
        internal static string ImportVirtualMachineCompleted {
            get {
                return ResourceManager.GetString("ImportVirtualMachineCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VirtualMachine creation failed with status : &apos;{0}&apos;.
        /// </summary>
        internal static string ImportVirtualMachineFailed {
            get {
                return ResourceManager.GetString("ImportVirtualMachineFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating virtual machine &apos;{0}&apos; in destination subscription for deployment {1}.
        /// </summary>
        internal static string ImportVirtualMachineStarted {
            get {
                return ResourceManager.GetString("ImportVirtualMachineStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual networks created successfully in ({0}:{1}:{2}:{3}).
        /// </summary>
        internal static string ImportVirtualNetworkCompleted {
            get {
                return ResourceManager.GetString("ImportVirtualNetworkCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating virtual networks in destination subscription..
        /// </summary>
        internal static string ImportVirtualNetworkStarted {
            get {
                return ResourceManager.GetString("ImportVirtualNetworkStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReservedIpName {0} does not exist in destination subscription. Please create the ReservedIPName before migrating the resources..
        /// </summary>
        internal static string MissingReservedIPName {
            get {
                return ResourceManager.GetString("MissingReservedIPName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReservedIPName {0} is already assiged to service {1} in destination subscription. The same ReservedIPName can not be assigned to muliple services..
        /// </summary>
        internal static string OccupiedReservedIpName {
            get {
                return ResourceManager.GetString("OccupiedReservedIpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validated input parameters.
        /// </summary>
        internal static string ParametersValidationCompleted {
            get {
                return ResourceManager.GetString("ParametersValidationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating input parameters.
        /// </summary>
        internal static string ParameterValidationStarted {
            get {
                return ResourceManager.GetString("ParameterValidationStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Name: {0} .  .
        /// </summary>
        internal static string ResourceName {
            get {
                return ResourceManager.GetString("ResourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Status updated at location &apos;{0}&apos;. In case of failure, please provide this file path to resume the import..
        /// </summary>
        internal static string ResumeImport {
            get {
                return ResourceManager.GetString("ResumeImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure occurred : Retry count {0}.
        /// </summary>
        internal static string RetryWait {
            get {
                return ResourceManager.GetString("RetryWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolled back affinity group : {0}  in ({1}:{2}:{3}:{4}).
        /// </summary>
        internal static string RollbackAffinityGroup {
            get {
                return ResourceManager.GetString("RollbackAffinityGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting all imported affinity groups from subscription.
        /// </summary>
        internal static string RollbackAffinityGroups {
            get {
                return ResourceManager.GetString("RollbackAffinityGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for affinity groups getting released...
        /// </summary>
        internal static string RollbackAffinityGroupsWaiting {
            get {
                return ResourceManager.GetString("RollbackAffinityGroupsWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolled back cloud service : {0} with deployments in ({1}:{2}:{3}:{4}).
        /// </summary>
        internal static string RollbackCloudService {
            get {
                return ResourceManager.GetString("RollbackCloudService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting all imported services and their deployments from subscription.
        /// </summary>
        internal static string RollbackCloudServices {
            get {
                return ResourceManager.GetString("RollbackCloudServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for services and their deployments getting released...
        /// </summary>
        internal static string RollbackCloudServicesWaiting {
            get {
                return ResourceManager.GetString("RollbackCloudServicesWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolled back all imported resources..
        /// </summary>
        internal static string RollbackCompleted {
            get {
                return ResourceManager.GetString("RollbackCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollback : Stage {0} of {1} completed....
        /// </summary>
        internal static string RollbackCompletedStages {
            get {
                return ResourceManager.GetString("RollbackCompletedStages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolled back Deployment : {0} for cloudservice {1}.
        /// </summary>
        internal static string RollbackDeployment {
            get {
                return ResourceManager.GetString("RollbackDeployment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured hence rolling back all imported resources..
        /// </summary>
        internal static string RollbackStarted {
            get {
                return ResourceManager.GetString("RollbackStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolled back storage account : {0}  in ({1}:{2}:{3}:{4}).
        /// </summary>
        internal static string RollbackStorageAccount {
            get {
                return ResourceManager.GetString("RollbackStorageAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting all imported storage accounts from subscription.
        /// </summary>
        internal static string RollbackStorageAccounts {
            get {
                return ResourceManager.GetString("RollbackStorageAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for dependencies of storages accounts getting released...
        /// </summary>
        internal static string RollbackStorageAccountsWaiting {
            get {
                return ResourceManager.GetString("RollbackStorageAccountsWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolled back Virtual Machine : {0}.
        /// </summary>
        internal static string RollbackVirtualMachine {
            get {
                return ResourceManager.GetString("RollbackVirtualMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolled back virtual networks.
        /// </summary>
        internal static string RollbackVirtualNetwork {
            get {
                return ResourceManager.GetString("RollbackVirtualNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting all imported virtual networks from subscription.
        /// </summary>
        internal static string RollbackVirtualNetworks {
            get {
                return ResourceManager.GetString("RollbackVirtualNetworks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for virtual networks getting released...
        /// </summary>
        internal static string RollbackVirtualNetworksWaiting {
            get {
                return ResourceManager.GetString("RollbackVirtualNetworksWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutting down all virtual machines of source subscription.
        /// </summary>
        internal static string ShutDownAllVms {
            get {
                return ResourceManager.GetString("ShutDownAllVms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutting down virtual machine {0} of source subscription.
        /// </summary>
        internal static string ShutDownVm {
            get {
                return ResourceManager.GetString("ShutDownVm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage account created in DC migration process..
        /// </summary>
        internal static string StorageAccountDescription {
            get {
                return ResourceManager.GetString("StorageAccountDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating Metadata File Resources....
        /// </summary>
        internal static string ValidateMetadataFileResources {
            get {
                return ResourceManager.GetString("ValidateMetadataFileResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating subscription capacity.
        /// </summary>
        internal static string ValidateSubscriptionCapacity {
            get {
                return ResourceManager.GetString("ValidateSubscriptionCapacity", resourceCulture);
            }
        }
    }
}
