
/*******************************************************************************
 * Copyright 2014 Persistent Systems Ltd.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/ServiceHosting/2011/07/NetworkConfiguration")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2011/07/NetworkConfiguration", IsNullable = false)]
public class NetworkConfiguration
{

    private NetworkConfigurationVirtualNetworkConfiguration virtualNetworkConfigurationField;

    /// <remarks/>
    public NetworkConfigurationVirtualNetworkConfiguration VirtualNetworkConfiguration
    {
        get
        {
            return this.virtualNetworkConfigurationField;
        }
        set
        {
            this.virtualNetworkConfigurationField = value;
        }
    }

    /// <summary>
    /// Status of Network Configuration import 
    /// </summary>
    [System.Xml.Serialization.XmlIgnore]
    public bool IsImported { get; set; }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/ServiceHosting/2011/07/NetworkConfiguration")]
public partial class NetworkConfigurationVirtualNetworkConfiguration
{

    private NetworkConfigurationVirtualNetworkConfigurationDns dnsField;

    private NetworkConfigurationVirtualNetworkConfigurationLocalNetworkSite[] localNetworkSitesField;

    private NetworkConfigurationVirtualNetworkConfigurationVirtualNetworkSite[] virtualNetworkSitesField;

    /// <remarks/>
    public NetworkConfigurationVirtualNetworkConfigurationDns Dns
    {
        get
        {
            return this.dnsField;
        }
        set
        {
            this.dnsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("LocalNetworkSite", IsNullable = false)]
    public NetworkConfigurationVirtualNetworkConfigurationLocalNetworkSite[] LocalNetworkSites
    {
        get
        {
            return this.localNetworkSitesField;
        }
        set
        {
            this.localNetworkSitesField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("VirtualNetworkSite", IsNullable = false)]
    public NetworkConfigurationVirtualNetworkConfigurationVirtualNetworkSite[] VirtualNetworkSites
    {
        get
        {
            return this.virtualNetworkSitesField;
        }
        set
        {
            this.virtualNetworkSitesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/ServiceHosting/2011/07/NetworkConfiguration")]
public partial class NetworkConfigurationVirtualNetworkConfigurationDns
{

    private NetworkConfigurationVirtualNetworkConfigurationDnsDnsServer[] dnsServersField;

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("DnsServer", IsNullable = false)]
    public NetworkConfigurationVirtualNetworkConfigurationDnsDnsServer[] DnsServers
    {
        get
        {
            return this.dnsServersField;
        }
        set
        {
            this.dnsServersField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/ServiceHosting/2011/07/NetworkConfiguration")]
public partial class NetworkConfigurationVirtualNetworkConfigurationDnsDnsServer
{

    private string nameField;

    private string iPAddressField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string IPAddress
    {
        get
        {
            return this.iPAddressField;
        }
        set
        {
            this.iPAddressField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/ServiceHosting/2011/07/NetworkConfiguration")]
public partial class NetworkConfigurationVirtualNetworkConfigurationLocalNetworkSite
{

    private string vPNGatewayAddressField;

    private NetworkConfigurationVirtualNetworkConfigurationLocalNetworkSiteAddressSpace addressSpaceField;

    private string nameField;

    /// <remarks/>
    public string VPNGatewayAddress
    {
        get
        {
            return this.vPNGatewayAddressField;
        }
        set
        {
            this.vPNGatewayAddressField = value;
        }
    }

    /// <remarks/>
    public NetworkConfigurationVirtualNetworkConfigurationLocalNetworkSiteAddressSpace AddressSpace
    {
        get
        {
            return this.addressSpaceField;
        }
        set
        {
            this.addressSpaceField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/ServiceHosting/2011/07/NetworkConfiguration")]
public partial class NetworkConfigurationVirtualNetworkConfigurationLocalNetworkSiteAddressSpace
{

    private string addressPrefixField;

    /// <remarks/>
    public string AddressPrefix
    {
        get
        {
            return this.addressPrefixField;
        }
        set
        {
            this.addressPrefixField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/ServiceHosting/2011/07/NetworkConfiguration")]
public partial class NetworkConfigurationVirtualNetworkConfigurationVirtualNetworkSite
{

    private NetworkConfigurationVirtualNetworkConfigurationVirtualNetworkSiteGateway gatewayField;

    private NetworkConfigurationVirtualNetworkConfigurationVirtualNetworkSiteDnsServerRef[] dnsServersRefField;

    private NetworkConfigurationVirtualNetworkConfigurationVirtualNetworkSiteSubnet[] subnetsField;

    private NetworkConfigurationVirtualNetworkConfigurationVirtualNetworkSiteAddressSpace addressSpaceField;

    private string nameField;

    private string affinityGroupField;

    private string locationField;

    /// <remarks/>
    public NetworkConfigurationVirtualNetworkConfigurationVirtualNetworkSiteGateway Gateway
    {
        get
        {
            return this.gatewayField;
        }
        set
        {
            this.gatewayField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("DnsServerRef", IsNullable = false)]
    public NetworkConfigurationVirtualNetworkConfigurationVirtualNetworkSiteDnsServerRef[] DnsServersRef
    {
        get
        {
            return this.dnsServersRefField;
        }
        set
        {
            this.dnsServersRefField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Subnet", IsNullable = false)]
    public NetworkConfigurationVirtualNetworkConfigurationVirtualNetworkSiteSubnet[] Subnets
    {
        get
        {
            return this.subnetsField;
        }
        set
        {
            this.subnetsField = value;
        }
    }

    /// <remarks/>
    public NetworkConfigurationVirtualNetworkConfigurationVirtualNetworkSiteAddressSpace AddressSpace
    {
        get
        {
            return this.addressSpaceField;
        }
        set
        {
            this.addressSpaceField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AffinityGroup
    {
        get
        {
            return this.affinityGroupField;
        }
        set
        {
            this.affinityGroupField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Location
    {
        get
        {
            return this.locationField;
        }
        set
        {
            this.locationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/ServiceHosting/2011/07/NetworkConfiguration")]
public partial class NetworkConfigurationVirtualNetworkConfigurationVirtualNetworkSiteGateway
{

    private NetworkConfigurationVirtualNetworkConfigurationVirtualNetworkSiteGatewayVPNClientAddressPool vPNClientAddressPoolField;

    private NetworkConfigurationVirtualNetworkConfigurationVirtualNetworkSiteGatewayConnectionsToLocalNetwork connectionsToLocalNetworkField;

    private string profileField;

    /// <remarks/>
    public NetworkConfigurationVirtualNetworkConfigurationVirtualNetworkSiteGatewayVPNClientAddressPool VPNClientAddressPool
    {
        get
        {
            return this.vPNClientAddressPoolField;
        }
        set
        {
            this.vPNClientAddressPoolField = value;
        }
    }

    /// <remarks/>
    public NetworkConfigurationVirtualNetworkConfigurationVirtualNetworkSiteGatewayConnectionsToLocalNetwork ConnectionsToLocalNetwork
    {
        get
        {
            return this.connectionsToLocalNetworkField;
        }
        set
        {
            this.connectionsToLocalNetworkField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string profile
    {
        get
        {
            return this.profileField;
        }
        set
        {
            this.profileField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/ServiceHosting/2011/07/NetworkConfiguration")]
public partial class NetworkConfigurationVirtualNetworkConfigurationVirtualNetworkSiteGatewayVPNClientAddressPool
{

    private string addressPrefixField;

    /// <remarks/>
    public string AddressPrefix
    {
        get
        {
            return this.addressPrefixField;
        }
        set
        {
            this.addressPrefixField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/ServiceHosting/2011/07/NetworkConfiguration")]
public partial class NetworkConfigurationVirtualNetworkConfigurationVirtualNetworkSiteGatewayConnectionsToLocalNetwork
{

    private NetworkConfigurationVirtualNetworkConfigurationVirtualNetworkSiteGatewayConnectionsToLocalNetworkLocalNetworkSiteRef localNetworkSiteRefField;

    /// <remarks/>
    public NetworkConfigurationVirtualNetworkConfigurationVirtualNetworkSiteGatewayConnectionsToLocalNetworkLocalNetworkSiteRef LocalNetworkSiteRef
    {
        get
        {
            return this.localNetworkSiteRefField;
        }
        set
        {
            this.localNetworkSiteRefField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/ServiceHosting/2011/07/NetworkConfiguration")]
public partial class NetworkConfigurationVirtualNetworkConfigurationVirtualNetworkSiteGatewayConnectionsToLocalNetworkLocalNetworkSiteRef
{

    private NetworkConfigurationVirtualNetworkConfigurationVirtualNetworkSiteGatewayConnectionsToLocalNetworkLocalNetworkSiteRefConnection connectionField;

    private string nameField;

    /// <remarks/>
    public NetworkConfigurationVirtualNetworkConfigurationVirtualNetworkSiteGatewayConnectionsToLocalNetworkLocalNetworkSiteRefConnection Connection
    {
        get
        {
            return this.connectionField;
        }
        set
        {
            this.connectionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/ServiceHosting/2011/07/NetworkConfiguration")]
public partial class NetworkConfigurationVirtualNetworkConfigurationVirtualNetworkSiteGatewayConnectionsToLocalNetworkLocalNetworkSiteRefConnection
{

    private string typeField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/ServiceHosting/2011/07/NetworkConfiguration")]
public partial class NetworkConfigurationVirtualNetworkConfigurationVirtualNetworkSiteDnsServerRef
{

    private string nameField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/ServiceHosting/2011/07/NetworkConfiguration")]
public partial class NetworkConfigurationVirtualNetworkConfigurationVirtualNetworkSiteSubnet
{

    private string addressPrefixField;

    private string nameField;

    /// <remarks/>
    public string AddressPrefix
    {
        get
        {
            return this.addressPrefixField;
        }
        set
        {
            this.addressPrefixField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/ServiceHosting/2011/07/NetworkConfiguration")]
public partial class NetworkConfigurationVirtualNetworkConfigurationVirtualNetworkSiteAddressSpace
{

    private string addressPrefixField;

    /// <remarks/>
    public string AddressPrefix
    {
        get
        {
            return this.addressPrefixField;
        }
        set
        {
            this.addressPrefixField = value;
        }
    }
}
